
The ''7-base_geometry'' module
============================

Using ''integer_validator''
---------------------

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Functional Cases:
----------------
1. Positive integers:

    >>> bg = BaseGeometry()
    >>> bg.integer_validator("my_int", 12)
    >>> bg.integer_validator("width", 89)

2. Value not an integer:

    >>> bg.integer_validator("name", "John")
    Traceback (most recent call last):
    TypeError: invalid type for name, integer expected

3. Value equal to zero:

    >>> bg.integer_validator("age", 0)
    Traceback (most recent call last):
    ValueError: invalid value for age, must be greater than 0

4. Negative value:

    >>> bg.integer_validator("distance", -4)
    Traceback (most recent call last):
    ValueError: invalid value for distance, must be greater than 0

5. Area method:

    >>> bg.area()
    Traceback (most recent call last):
    NotImplementedError: area() method not implemented


Edge Cases:
----------

6. No arguments:

    >>> bg.integer_validator()
    Traceback (most recent call last):
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

7. NameError:

    >>> bg.integer_validator(test)
    Traceback (most recent call last):
    NameError: name 'test' is not defined

8. Missing value argument:

    >>> bg.integer_validator("distance",)
    Traceback (most recent call last):
    TypeError: integer_validator() missing 1 required positional argument: 'value'

9. Missing name argument:

    >>> bg.integer_validator(, 5)
    Traceback (most recent call last):
    SyntaxError: invalid syntax

10. More than 2 arguments:

    >>> bg.integer_validator("distance", 5, 7)
    Traceback (most recent call last):
    TypeError: integer_validator() takes 3 positional arguments but 4 were given

11. Value as a float:

    >>> bg.integer_validator("area", 12.5)
    Traceback (most recent call last):
    TypeError: invalid type for area, integer expected

12. Value as infinity:

    >>> bg.integer_validator("area", float('inf'))
    Traceback (most recent call last):
    TypeError: invalid type for area, integer expected

13. Value as a boolean:

    >>> bg.integer_validator("area", False)
    Traceback (most recent call last):
    TypeError: invalid type for area, integer expected

14. Value as a tuple:

    >>> bg.integer_validator("area", (7, 8))
    Traceback (most recent call last):
    TypeError: invalid type for area, integer expected

15. Value as a list:

    >>> bg.integer_validator("area", [1, 2, 3])
    Traceback (most recent call last):
    TypeError: invalid type for area, integer expected

16. Value as a set:

    >>> bg.integer_validator("area", {1, 2, 3})
    Traceback (most recent call last):
    TypeError: invalid type for area, integer expected

17. Value as None:

    >>> bg.integer_validator("area", None)
    Traceback (most recent call last):
    TypeError: invalid type for area, integer expected

18. Empty string as name:

    >>> bg.integer_validator("", 5)

19. Value as NaN:

    >>> bg.integer_validator("area", float('nan'))
    Traceback (most recent call last):
    TypeError: invalid type for area, integer expected

20. Try to convert string to float:

    >>> bg.integer_validator("area", float('test'))
    Traceback (most recent call last):
    ValueError: could not convert string to float: 'test'
